version: "3.7"
services:
  bot:
    build: .
    volumes:
      # this is for development only as it makes our code accesable from the host pc
      # remove for production
      - .:/obsidion
    links:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:12-alpine
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: discord
      POSTGRES_PASSWORD: hunter12
      POSTGRES_USER: discord
    ports:
      - "5432"
  redis:
    image: redis:alpine

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgresdb:
